# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_estudiante', models.CharField(max_length=10)),
                ('carrera_estudiante', models.CharField(choices=[('P', 'Profundización'), ('I', 'Investigación'), ('D', 'Doctorado')], max_length=1)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_evaluador', models.AutoField(primary_key=True, serialize=False)),
                ('escolaridad_evaluador', models.CharField(choices=[('M', 'Maestria'), ('D', 'Doctorado')], max_length=1)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Filiacion',
            fields=[
                ('id_filiacion', models.AutoField(primary_key=True, serialize=False)),
                ('universidad_filiacion', models.CharField(max_length=50)),
                ('departamento_filiacion', models.CharField(max_length=50)),
                ('grupo_filiacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='secretaria',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_secretaria', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('escolaridad_tutor', models.CharField(choices=[('M', 'Maestria'), ('D', 'Doctorado')], max_length=1)),
                ('filiacion_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Filiacion')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_actor', models.CharField(choices=[('S', 'Estudiante'), ('T', 'Tutor'), ('C', 'Coordinador'), ('E', 'Evaluador'), ('O', 'Secretaria')], max_length=1)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='evaluador',
            name='filiacion_evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Filiacion'),
        ),
    ]
