# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170411_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_carrera',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Carrera'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_escolaridad',
            field=models.CharField(blank=True, choices=[('M', 'Maestria'), ('D', 'Doctorado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_filiacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Filiacion'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='registro_aula',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='registro',
            name='registro_observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
