# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170418_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Carrera'),
        ),
    ]
